services:
  - type: web
    name: safecall-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: STT_RU_API_KEY
        sync: false
      - key: STT_KZ_API_KEY
        sync: false